# Generated by Django 5.0.6 on 2024-06-02 07:25

import django.db.models.deletion
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=255)),
                ('body', wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True)),
                ('category', models.CharField(choices=[('პოლიტიკა', '#FF8CDF'), ('საზოგადოება', '#FFE500'), ('ჯანმრთელობა', '#00FA0A'), ('ეკონომიკა', '#FF7A00'), ('კულტურა', '#FA00FF'), ('სპორტი', '#FF0000'), ('ჩემი ქალაქი', '#2500FF'), ('მსოფლიო', '#8BF8FF'), ('ინტერვიუ', '#0094FF'), ('გადაცემები', '#6B2000'), ('ვიდეობლოგი', '#D9C2FF')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
