# Generated by Django 5.0.6 on 2024-06-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='category',
            new_name='dot',
        ),
    ]
