# Generated by Django 5.0.6 on 2024-07-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_category_blogpage_dot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='dot',
            field=models.CharField(choices=[('#FF8CDF', 'პოლიტიკა'), ('#FFE500', 'საზოგადოება'), ('#00FA0A', 'ჯანმრთელობა'), ('#FF7A00', 'ეკონომიკა'), ('#FA00FF', 'კულტურა'), ('#FF0000', 'სპორტი'), ('#2500FF', 'ჩემი ქალაქი'), ('#8BF8FF', 'მსოფლიო'), ('#0094FF', 'ინტერვიუ'), ('#6B2000', 'გადაცემები'), ('#D9C2FF', 'ვიდეობლოგი')], max_length=50),
        ),
    ]
