# Generated by Django 5.0.6 on 2024-07-06 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_category_blogpage_dot'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='dot',
            field=models.CharField(choices=[('#FF8CDF', 'პოლიტიკა'), ('#FFE500', 'საზოგადოება'), ('#00FA0A', 'ჯანმრთელობა'), ('#FF7A00', 'ეკონომიკა'), ('#FA00FF', 'კულტურა'), ('#FF0000', 'სპორტი'), ('#2500FF', 'ჩემი ქალაქი'), ('#8BF8FF', 'მსოფლიო'), ('#0094FF', 'ინტერვიუ'), ('#6B2000', 'გადაცემები'), ('#D9C2FF', 'ვიდეობლოგი')], max_length=50),
        ),
    ]
