# Generated by Django 5.0.6 on 2024-07-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blogpage_dot'),
        ('api', '0005_alter_blogpage_video_delete_video'),
    ]

    operations = [
    ]
