# Generated by Django 5.0.6 on 2024-07-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blogpage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='in_slider',
            field=models.BooleanField(default=False, verbose_name='Include in slider'),
        ),
    ]
