# Generated by Django 5.0.6 on 2024-08-04 17:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blogpage_in_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='text',
            field=wagtail.fields.RichTextField(),
        ),
    ]
