# Generated by Django 5.0.6 on 2024-08-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_advertisementpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementpage',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
