# Generated by Django 5.0.6 on 2024-08-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_advertisementpage_link'),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtaildocs', '0013_delete_uploadeddocument'),
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('wagtailvideos', '0015_video_height_video_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementpage',
            name='ad_number',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='advertisementpage',
            constraint=models.UniqueConstraint(fields=('ad_number',), name='unique_ad_number'),
        ),
    ]
