# Generated by Django 5.0.6 on 2024-08-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_advertisementpage_ad_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementpage',
            name='ad_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
