# Generated by Django 5.0.6 on 2024-08-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_advertisementpage_ad_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementpage',
            name='ad_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Position 1'), (2, 'Position 2'), (3, 'Position 3'), (4, 'Position 4')], unique=True),
        ),
    ]
