# Generated by Django 5.0.6 on 2024-08-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_advertisementpage_ad_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='custom_order',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
