# Generated by Django 5.0.6 on 2024-08-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_blogpage_custom_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='custom_order',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
