# Generated by Django 5.0.6 on 2024-08-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_category_parent_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('nutrition', 'Nutrition'), ('mental_health', 'Mental Health'), ('exercise', 'Exercise')], max_length=50, null=True),
        ),
    ]
