# Generated by Django 5.0.6 on 2024-08-26 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_answer_quizpage_answer_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizpage',
            old_name='answers',
            new_name='Answer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.quizpage'),
        ),
    ]
