# Generated by Django 5.0.6 on 2024-08-26 08:42

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_answer_quiz_quiz_delete_quizpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='quiz',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='api.quiz'),
        ),
    ]
