# Generated by Django 5.0.6 on 2024-08-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_answer_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='num_answers',
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer1',
            field=models.CharField(max_length=255, null=True, verbose_name='Answer 1'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer1_is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Answer 1 Correct?'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer2',
            field=models.CharField(max_length=255, null=True, verbose_name='Answer 2'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer2_is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Answer 2 Correct?'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer3',
            field=models.CharField(max_length=255, null=True, verbose_name='Answer 3'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer3_is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Answer 3 Correct?'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer4',
            field=models.CharField(max_length=255, null=True, verbose_name='Answer 4'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer4_is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Answer 4 Correct?'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
