# Generated by Django 5.0.6 on 2024-08-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_quiz_answer1_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
    ]
